Support setting client timeout in config file
hugegraph/hugegraph-studio pull request #11
Opened 2018-12-25 14:56 UTC by Linary

Implement #8

2018-12-26 09:46 UTC, javeme submitted a review, later dismissed

2018-12-26 09:46 UTC, javeme commented on studio-dist/src/assembly/static/conf/hugegraph-studio.properties
> +client.timeout=20
remove space before " graph.server.port"(line 5)

2018-12-26 09:46 UTC, javeme commented on studio-api/src/main/java/com/baidu/hugegraph/studio/config/StudioApiOptions.java
> +                    "The timeout of hugegraph client",
The timeout of hugegraph client in seconds

2019-02-27 06:57 UTC, javeme requested changes

2019-02-27 06:57 UTC, javeme commented on studio-api/src/main/java/com/baidu/hugegraph/studio/config/StudioApiOptions.java
> +                    20
keep 30s

2019-02-27 06:57 UTC, javeme commented on studio-dist/src/assembly/static/conf/hugegraph-studio.properties
> +client.timeout=20
keep 30s

2019-02-27 07:35 UTC, javeme approved these changes

2019-02-27 07:53 UTC, zhoney approved these changes

2019-02-27 07:54 UTC, merged