Close client when HugeGraphStudio shutdown
hugegraph/hugegraph-studio pull request #24
Opened 2019-06-03 11:10 UTC by Linary

2019-06-03 11:43 UTC, javeme requested changes

2019-06-03 11:43 UTC, javeme commented on studio-api/src/main/java/com/baidu/hugegraph/studio/board/HugeClientWrapper.java
> + * Copyright (C) 2019 Baidu, Inc. All Rights Reserved.
apache 2 licence

2019-06-03 11:43 UTC, javeme commented on studio-api/src/main/java/com/baidu/hugegraph/studio/config/StudioApiConfig.java
> +            userDataDir = ".hugegraph-studio";
add a const var

2019-06-06 03:45 UTC, javeme requested changes

2019-06-06 03:45 UTC, javeme commented on studio-api/src/main/java/com/baidu/hugegraph/studio/board/service/BoardService.java
> +            client = HugeClientWrapper.get(conf);
also pass error message to browser

2019-06-06 03:45 UTC, javeme commented on studio-dist/src/main/java/com/baidu/hugegraph/studio/HugeGraphStudio.java
> +                    System.out.println("stop studio server");
remove it

2019-06-14 03:08 UTC, zhoney requested changes

2019-06-14 03:08 UTC, zhoney commented on studio-api/src/main/java/com/baidu/hugegraph/studio/board/service/BoardService.java
> +            result.setMessage("Failed to connect HugeGraphServer" + e);
add ": " to keep consistent with line 143

2019-06-14 09:56 UTC, javeme approved these changes

2019-06-14 12:20 UTC, zhoney approved these changes

2019-06-14 12:21 UTC, merged