pom.xml: fix antrun plugin build
hugegraph/hugegraph-studio pull request #25
Opened 2019-06-19 13:32 UTC by choleraehyq

Or else it will fail to build:
```
➜  hugegraph-studio git:(master) mvn package -DskipTests -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] hugegraph-studio                                                   [pom]
[INFO] studio-api                                                         [war]
[INFO] studio-dist                                                        [jar]
[INFO]
[INFO] ----------------< com.baidu.hugegraph:hugegraph-studio >----------------
[INFO] Building hugegraph-studio 0.9.0                                    [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] -------------------< com.baidu.hugegraph:studio-api >-------------------
[INFO] Building studio-api 0.9.0                                          [2/3]
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ studio-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ studio-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ studio-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/cholerae/Documents/javacode/hugegraph-studio/studio-api/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ studio-api ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ studio-api ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-war-plugin:2.1.1:war (default-war) @ studio-api ---
[INFO] Packaging webapp
[INFO] Assembling webapp [studio-api] in [/Users/cholerae/Documents/javacode/hugegraph-studio/studio-api/target/studio-api]
[INFO] Processing war project
[INFO] Copying webapp webResources [/Users/cholerae/Documents/javacode/hugegraph-studio/studio-api/src/main/webapp/WEB-INF] to [/Users/cholerae/Documents/javacode/hugegraph-studio/studio-api/target/studio-api]
[INFO] Copying webapp resources [/Users/cholerae/Documents/javacode/hugegraph-studio/studio-api/src/main/webapp]
[INFO] Webapp assembled in [358 msecs]
[INFO] Building war: /Users/cholerae/Documents/javacode/hugegraph-studio/studio-api/target/studio-api.war
[INFO] WEB-INF/web.xml already added, skipping
[INFO]
[INFO] ------------------< com.baidu.hugegraph:studio-dist >-------------------
[INFO] Building studio-dist 0.9.0                                         [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ studio-dist ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/cholerae/Documents/javacode/hugegraph-studio/studio-dist/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ studio-dist ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ studio-dist ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/cholerae/Documents/javacode/hugegraph-studio/studio-dist/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ studio-dist ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ studio-dist ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ studio-dist ---
[INFO]
[INFO] --- maven-assembly-plugin:2.4:single (install-studio) @ studio-dist ---
[INFO] Copying files to /Users/cholerae/Documents/javacode/hugegraph-studio/studio-dist/../hugegraph-studio-0.9.0
[INFO]
[INFO] --- maven-antrun-plugin:1.3:run (default) @ studio-dist ---
[INFO] Executing tasks
     [exec] env: node: No such file or directory
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for hugegraph-studio 0.9.0:
[INFO]
[INFO] hugegraph-studio ................................... SUCCESS [  0.011 s]
[INFO] studio-api ......................................... SUCCESS [  3.477 s]
[INFO] studio-dist ........................................ FAILURE [  2.464 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.173 s
[INFO] Finished at: 2019-06-19T20:56:05+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.3:run (default) on project studio-dist: An Ant BuildException has occured: exec returned: 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.3:run (default) on project studio-dist: An Ant BuildException has occured: exec returned: 1
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: exec returned: 1
    at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks (AbstractAntMojo.java:131)
    at org.apache.maven.plugin.antrun.AntRunMojo.execute (AntRunMojo.java:98)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at or [...]

2019-06-19 13:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hugegraph/hugegraph-studio?pullRequest=25) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hugegraph/hugegraph-studio?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hugegraph/hugegraph-studio?pullRequest=25) it.</sub>

2019-06-20 03:00 UTC, choleraehyq commented
@Linary PTAL

2019-06-20 03:21 UTC, Linary commented
After your modification, it seems that `mvn package -DskipTests -e` can't generate hugegraph-studio-0.9.0.tar.gz
Please check it.

2019-06-20 03:32 UTC, Linary requested changes

2019-06-20 03:32 UTC, Linary commented on studio-dist/pom.xml
>  </project>
add an empty line after line 154

2019-06-26 07:31 UTC, Linary commented
```
[exec] env: node: No such file or directory
```
seems you should install nodejs env

2019-11-26 13:10 UTC, zhoney commented
Close due to long time no comments and activities.

2019-11-26 13:10 UTC, closed without merging